feed/urls.py
from django.urls import path

from . import views

app_name = "feed"

urlpatterns = [ 
    path("", views.HomePage.as_view(), name="index"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("new/", views.CreateNewPost.as_view(), name="new_post"),
]

til/urls.py
from django.contrib import admin
from django.urls import path, re_path as url
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings 

from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(feed_urls, namespace="feed")),
    url("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    text = models.CharField(max_length=240)
    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User,
        on_delete= models.CASCADE,
    )
    
    def __str__(self):
        return self.text[0:100]
    

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name = "profile"
    )
    image = ImageField(upload_to='profiles')
    
    def __str__(self):
        return self.user.username


@receiver(post_save, sender = User)
def create_user_profile(sender, instance, created, **kwargs):
    """ Create a new Profile() object when a Django user is created """
    if created:
        Profile.objects.create(user=instance)

feed/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Post

class HomePage(ListView):
    http_method_names = ["get"]
    template_name = "feed/homepage.html"
    model = Post
    context_object_name = "posts"
    queryset = Post.objects.all().order_by('-id')[0:30]

class PostDetailView(DetailView):
    http_method_names = ["get"]
    template_name = "feed/detail.html"
    model = Post
    context_object_name = "post"
    
class CreateNewPost(LoginRequiredMixin, CreateView):
    model = Post
    template_name = "feed/create.html"
    fields = ['text'] 
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return super().form_valid(form)

profiles/views.py
from django.shortcuts import render

# Create your views here.

feed/templates/feed/create.html
{% extends "base.html" %}

{% block title %}Create a new post{% endblock title %}

{% block body %}
    <form method="POST" action=".">
        {% csrf_token %}
        {{form.as_p}}
        <div>
            <div class="my-3">
                <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center" type="submit">
                <span class="mr-2">Create post</span>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                    <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                </svg>
                </button>
            </div>
        </div>
    </form>
{% endblock body %}

feed/templates/feed/detail.html
{% extends "base.html" %}

{% block title %}{{ post.text }} by {{ post.author.username }}{% endblock %}

{% block body %}
    {% include "includes/post.html" with post=post  %}
{% endblock body %}

feed/templates/feed/homepage.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}Homepage{% endblock %}

{% block body %}
    {% for post in posts %}
        {% include "includes/post.html" with post=post show_detail_link=True %}
    {% endfor %}
{% endblock body %}

til/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default title{% endblock %}</title>

    <!-- Adding Tailwind css cdn -->
    <script src="https://cdn.tailwindcss.com"></script>

    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />

</head>

<body>

    <!-- component is from https://tailwindcomponents.com/component/sidebar-navigation -->

    <div class="min-h-screen flex flex-row bg-gray-100">
        <div class="flex flex-col w-56 bg-white rounded-r-3xl overflow-hidden">
            <div class="flex items-center justify-center h-20 shadow-md">
                <h1 class="text-3xl uppercase text-indigo-500">TIL</h1>
            </div>
            <ul class="flex flex-col py-4">
            <li>
                <a href="/" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-home"></i></span>
                <span class="text-sm font-medium">Home</span>
                </a>
            </li>
            
            {% if request.user.is_authenticated %}
                <li>
                    <a href="{% url 'feed:new_post' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                    <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-layer-plus"></i></span>
                    <span class="text-sm font-medium">New post</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'account_logout' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                    <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-out"></i></span>
                    <span class="text-sm font-medium">Logout</span>
                    </a>
                </li>
                
            {% else %}
                <li>
                    <a href="{% url 'account_login' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                    <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-in"></i></span>
                    <span class="text-sm font-medium">Login</span>
                    </a>
                </li>
            {% endif %}
            </ul>
        </div>

        <div class="p-16">
            {% block body %}
                {% block content %}{% endblock content %}
            {% endblock body %}
        </div>

        {% if request.user.is_authenticated %}
            <!-- component is from https://tailwindcomponents.com/component/a-minimal-simple-modal-that-still-looks-good -->
            <div class="flex items-center justify-center fixed left-0 bottom-0 w-full h-full bg-gray-800 bg-opacity-75 hidden js-modal">
                <div class="bg-white rounded-lg w-1/2">
                    <div class="flex flex-col items-start p-4">
                        <div class="flex items-center w-full">
                            <div class="text-gray-900 font-medium text-lg">New post</div>
                            <svg class="ml-auto fill-current text-gray-700 w-6 h-6 cursor-pointer" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
                                <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"/>
                            </svg>
                        </div>
                        <hr>
                        <div class=""> {# TODO: Add the ajax form #}</div>
                        <hr>
                        <div class="ml-auto">
                            <button class="bg-white text-sm text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-1 px-3 mt-4 inline-flex items-center js-submit" type="button">
                            <span class="mr-2">Create post</span>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                            </svg>
                            </button>
                        </div>
                    </div>
                </div>  
            </div>
        {% endif %}
    </div>


</body>
</html>

til/templates/includes/post.html
{% load thumbnail %}

<!-- component from https://tailwindcomponents.com/component/post-article -->
<div class="max-w-4xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" style="width: 50rem">   
    <div class="flex justify-between items-center">
        <span class="font-light text-gray-600">{{post.date|date:"F j, Y, g:i a"}}</span>
        {% comment %} <a class="px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-gray-500" href="#">Design</a> {% endcomment %}
    </div>
    <div class="mt-2">
        {% comment %} <a class="text-2xl text-gray-700 font-bold hover:text-gray-600" href="#">Accessibility tools for designers and developers</a> {% endcomment %}
        <p class="mt-2 text-gray-600">{{post.text}}</p>
    </div>
    <div class="flex justify-between items-center mt-4">
        {% if show_detail_link %}
            <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id %}">
                Read more
            </a>
        {% else %}
            <span>&nbsp</span>
        {% endif %}
        <div>
            {# TODO: add url below #}
            <a class="flex items-center" href="#">
                {% thumbnail post.author.profile.image "373x373" crop="center" as im %}
                    <img class="mx-4 w-10 h-10 object-cover rounded-full hidden sm:block" src="{{im.url}}" alt="avatar">
                {% endthumbnail %}
                <h1 class="text-gray-700 font-bold"> {{post.author.username}} </h1>
            </a>
        </div>
    </div>
</div>
<hr>